name: Build Executables

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executables
        run: |
          pyinstaller --onefile --name main-mac main.py
          pyinstaller --onefile --name main-linux main.py
          pyinstaller --onefile --name main-win main.py
          mkdir dist
          mv dist/main-mac dist/main-mac
          mv dist/main-linux dist/main-linux
          mv dist/main-win.exe dist/main-win.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: |
            dist/main-mac
            dist/main-linux
            dist/main-win.exe
